-- Seed Data for Acervo (Themes)

INSERT INTO public.acervo (nome, categoria, localizacao, apelidos) VALUES
-- Papel 1
('Sonic', 'Tema', 'Papel 1', ARRAY['Sonic the Hedgehog']),
('Dragão bool', 'Tema', 'Papel 1', ARRAY['Dragon Ball', 'Dragon Ball Z', 'DBZ']),
('Divertidamente', 'Tema', 'Papel 1', ARRAY['Inside Out']),
('Trem', 'Tema', 'Papel 1', ARRAY['Trenzinho']),
('Chá Casa Nova', 'Tema', 'Papel 1', ARRAY['Chá de Panela', 'Chá de Cozinha', 'Casa Nova']),
('Realeza', 'Tema', 'Papel 1', ARRAY['Príncipe', 'Realeza Menino', 'Realeza Menina']),
('Picachu', 'Tema', 'Papel 1', ARRAY['Pikachu', 'Pokémon', 'Pokemon']),
('Gatinha Marie', 'Tema', 'Papel 1', ARRAY['Marie']),
('Peppa', 'Tema', 'Papel 1', ARRAY['Peppa Pig']),
('Cinderela', 'Tema', 'Papel 1', ARRAY[]::TEXT[]),
('Luna', 'Tema', 'Papel 1', ARRAY['O Show da Luna']),
('Branca Neve', 'Tema', 'Papel 1', ARRAY['Branca de Neve']),
('Melancia', 'Tema', 'Papel 1', ARRAY['Magali', 'Festa Melancia']),
('Bobbie Goods', 'Tema', 'Papel 1', ARRAY[]::TEXT[]),
('Baskete', 'Tema', 'Papel 1', ARRAY['Basquete', 'Basketball']),
('Galáxia', 'Tema', 'Papel 1', ARRAY['Astronauta', 'Espaço']),
('Flamingo', 'Tema', 'Papel 1', ARRAY['Tropical', 'Festa Flamingo']),
('Espírito Santo', 'Tema', 'Papel 1', ARRAY['Batizado', 'Primeira Eucaristia']),
('Fé', 'Tema', 'Papel 1', ARRAY['Religioso']),
('Aliança', 'Tema', 'Papel 1', ARRAY['Noivado', 'Casamento', 'Bodas']),
('Dálmatas', 'Tema', 'Papel 1', ARRAY['101 Dálmatas']),
('Galinha Pintadinha', 'Tema', 'Papel 1', ARRAY[]::TEXT[]),
('As princesas', 'Tema', 'Papel 1', ARRAY['Princesas', 'Princesas Disney']),
('Bita', 'Tema', 'Papel 1', ARRAY['Mundo Bita']),
('Super Mario', 'Tema', 'Papel 1', ARRAY['Mario', 'Mario Bros']),
('Circo', 'Tema', 'Papel 1', ARRAY['Circo Mágico', 'Circo Vintage']),

-- Papel 2
('Monstros S/A', 'Tema', 'Papel 2', ARRAY['Monstros SA', 'Mike Wazowski']),
('Carros', 'Tema', 'Papel 2', ARRAY['Relâmpago McQueen', 'Disney Carros']),
('Ursinho', 'Tema', 'Papel 2', ARRAY['Ursinho Baloeiro', 'Ursinho Príncipe']),
('Fundo mar', 'Tema', 'Papel 2', ARRAY['Fundo do Mar', 'Sereia', 'Oceano']),
('Chuvas benção', 'Tema', 'Papel 2', ARRAY['Chuva de Bênçãos', 'Chuva de Amor']),
('Jesus', 'Tema', 'Papel 2', ARRAY['Religioso Jesus']),
('Dino baby', 'Tema', 'Papel 2', ARRAY['Dinossauro Baby']),
('Fortaleza', 'Tema', 'Papel 2', ARRAY['Fortaleza EC', 'Tricolor', 'Leão']),
('Ceará', 'Tema', 'Papel 2', ARRAY['Ceará SC', 'Vozão']),
('Flamengo', 'Tema', 'Papel 2', ARRAY['Mengão', 'CRF']),
('Preto Dourado', 'Tema', 'Papel 2', ARRAY['Preto e Dourado', 'Adulto Preto e Dourado']),
('Super men baby', 'Tema', 'Papel 2', ARRAY['Super Homem Baby', 'Superman Baby']),
('Adulto', 'Tema', 'Papel 2', ARRAY['Festa Adulto', 'Festa Boteco Adulto']),
('Ursinha', 'Tema', 'Papel 2', ARRAY['Ursinha Princesa', 'Ursinha Baloeira']),
('Bailarina', 'Tema', 'Papel 2', ARRAY['Festa Bailarina']),
('Elefantinho', 'Tema', 'Papel 2', ARRAY['Elefantinho Chevron', 'Chá de Bebê Elefantinho']),
('Bodas Rosas', 'Tema', 'Papel 2', ARRAY['Bodas', 'Banda Rosas']),
('3 Palavrinhas', 'Tema', 'Papel 2', ARRAY['Três Palavrinhas']),
('São João', 'Tema', 'Papel 2', ARRAY['Festa Junina', 'Arraiá']),
('Alice', 'Tema', 'Papel 2', ARRAY['Alice no País das Maravilhas']),
('Sky', 'Tema', 'Papel 2', ARRAY['Skye', 'Patrulha Canina Skye']),
('Nossa senhora', 'Tema', 'Papel 2', ARRAY['Nossa Senhora Aparecida', 'Religioso Maria']),
('Bolo fofo', 'Tema', 'Papel 2', ARRAY['Bolofofos']),
('Capivara', 'Tema', 'Papel 2', ARRAY[]::TEXT[]),
('Sófia', 'Tema', 'Papel 2', ARRAY['Princesinha Sofia', 'Princesa Sofia']),
('Cristiano Ronaldo', 'Tema', 'Papel 2', ARRAY['CR7', 'Futebol CR7']),
('Boteco', 'Tema', 'Papel 2', ARRAY['Festa Boteco']),
('Dinossauro', 'Tema', 'Papel 2', ARRAY['Parque dos Dinossauros', 'Jurassic Park']),
('3 Poderosos', 'Tema', 'Papel 2', ARRAY['Os 3 Poderosos']),
('Futebol', 'Tema', 'Papel 2', ARRAY['Festa Futebol', 'Tema Futebol']),
('Lillo & stich', 'Tema', 'Papel 2', ARRAY['Lilo e Stitch', 'Stitch']),
('Bela fera', 'Tema', 'Papel 2', ARRAY['A Bela e a Fera', 'Beauty and the Beast']),
('Homem Aranha', 'Tema', 'Papel 2', ARRAY['Spider', 'Spiderman', 'Miranha']),
('Vingadores', 'Tema', 'Papel 2', ARRAY['Avengers']),
('Azul Dourado', 'Tema', 'Papel 2', ARRAY['Azul e Dourado', 'Realeza Azul e Dourado']),
('SAFARY', 'Tema', 'Papel 2', ARRAY['Safari', 'Selva', 'Safari Baby']),
('Poderoso chefinho', 'Tema', 'Papel 2', ARRAY['O Poderoso Chefinho', 'Boss Baby']),

-- Papel 3
('Princesa sapo', 'Tema', 'Papel 3', ARRAY['A Princesa e o Sapo', 'Tiana']),
('Barbi', 'Tema', 'Papel 3', ARRAY['Barbie']),
('Ariel', 'Tema', 'Papel 3', ARRAY['Pequena Sereia', 'A Pequena Sereia']),
('Peixinho', 'Tema', 'Papel 3', ARRAY['Nemo', 'Procurando Nemo']),
('Mini vermelha', 'Tema', 'Papel 3', ARRAY['Minnie', 'Minnie Vermelha']),
('Jardim', 'Tema', 'Papel 3', ARRAY['Jardim Encantado', 'Jardim das Borboletas']),
('Mine craff', 'Tema', 'Papel 3', ARRAY['Minecraft']),
('Wandinha', 'Tema', 'Papel 3', ARRAY['Wednesday', 'Família Addams']),
('Batman', 'Tema', 'Papel 3', ARRAY['Morcego']),
('Borboleta', 'Tema', 'Papel 3', ARRAY['Jardim das Borboletas', 'Borboletas']),
('Rosas vermelha, amarelo, Roseo', 'Tema', 'Papel 3', ARRAY['Rosas', 'Floral']),
('Hulk', 'Tema', 'Papel 3', ARRAY['O Incrível Hulk']),
('Rapunzel', 'Tema', 'Papel 3', ARRAY['Enrolados', 'Tangled']),
('Bebe fin', 'Tema', 'Papel 3', ARRAY['Bebê Finn', 'Bebe Finn']),
('Patrulha canina', 'Tema', 'Papel 3', ARRAY['Paw Patrol']),
('Revelação', 'Tema', 'Papel 3', ARRAY['Chá Revelação', 'Menino ou Menina']),
('Hot whell', 'Tema', 'Papel 3', ARRAY['Hot Wheels', 'Carros Hot Wheels']),
('Princesa Valente', 'Tema', 'Papel 3', ARRAY['Valente', 'Merida']),
('Moana baby', 'Tema', 'Papel 3', ARRAY['Moana']),
('Bento Flork', 'Tema', 'Papel 3', ARRAY['Flork', 'Bento Cake', 'Bento Toto']),
('Cebolinha', 'Tema', 'Papel 3', ARRAY['Turma da Mônica Cebolinha']),
('Unicórnio', 'Tema', 'Papel 3', ARRAY['Unicorn']),
('Free fire', 'Tema', 'Papel 3', ARRAY['FF']),
('Tardezinha', 'Tema', 'Papel 3', ARRAY['Festa Tardezinha', 'Pagode']),
('Rei Leão', 'Tema', 'Papel 3', ARRAY['The Lion King', 'Simba']),
('Fazendinha', 'Tema', 'Papel 3', ARRAY['Festa Fazendinha', 'Fazenda']),
('Dia Namorados', 'Tema', 'Papel 3', ARRAY['Namorados', 'Romântico']),
('Paris', 'Tema', 'Papel 3', ARRAY['Festa Paris']),
('Pool party', 'Tema', 'Papel 3', ARRAY['Festa na Piscina', 'Neon Pool Party']),
('ONE PEACE', 'Tema', 'Papel 3', ARRAY['One Piece', 'Luffy']),
('Anjinho', 'Tema', 'Papel 3', ARRAY['Anjo', 'Batizado Anjinho']),
('Gratidão', 'Tema', 'Papel 3', ARRAY[]::TEXT[]),
('Sherek / Fiona', 'Tema', 'Papel 3', ARRAY['Shrek', 'Fiona']),
('United', 'Tema', 'Papel 3', ARRAY['Now United']),
('Frozen', 'Tema', 'Papel 3', ARRAY['Elsa', 'Anna', 'Olaf']),
('Toy Story', 'Tema', 'Papel 3', ARRAY['Woody', 'Buzz', 'Buzz Lightyear']),
('Arlequina', 'Tema', 'Papel 3', ARRAY['Harley Quinn', 'Esquadrão Suicida']),
('p/ Mãe', 'Tema', 'Papel 3', ARRAY['Dia das Mães', 'Festa Mãe']),
('15 Anos', 'Tema', 'Papel 3', ARRAY['Debutante']);
